# Site settings
title: Azizur Rahman
description: > # this means to ignore newlines until "baseurl:"
  Senior Technical Architect at Big British Castle (@BBC) and CTO @mahabbawedding<br /><br />Azizur is a Senior Technical Architect, at BBC's Technology Strategy and Architecture team. He focuses on enabling conversations with the BBC using voice assistant platforms such as Amazon Alexa, Google Home, Microsoft Cortana and Apple Siri. Recently he and his team launched the "OK Beeb", BBC voice assistant.<br /><br />Outside of his day job, Azizur is building, Mahabba Wedding, a digital wedding invitation service for Muslims, helping couples announce their celebration and making it easy to manage guest RSVPs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://azizur.com" # the base hostname & protocol for your site

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

social-icons:
  - title: GitHub
    username: azizur
    url: https://github.com
    class: github
  - title: Twitter
    username: azizur
    url: https://twitter.com
    class: twitter
  - title: LinkedIn
    username: azizurrahman
    url: https://uk.linkedin.com/in
    class: linkedin

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

# Compress HTML
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

theme: jekyll-theme-modernist
